name: erc20indexer
description: ERC-20 indexer
networks:
  - id: 80085 # Berachain Artio Testnet
    start_block: 0
    contracts:
      - name: ERC20
        address: "0xB734c264F83E39Ef6EC200F99550779998cC812d" #MIM
        handler: src/EventHandlers.ts
        events:
          - event: "Approval(address indexed owner, address indexed spender, uint256 value)"
            requiredEntities:
              - name: "Account"
              - name: "Approval"
          - event: "Transfer(address indexed from, address indexed to, uint256 value)"
            requiredEntities:
              - name: "Account"
              - name: "Approval"
